# Database configuration
# Example:
# db.url=jdbc:mysql://localhost:3306/pharmacy_db
# db.user=root
# db.password=TB20010415

# Uncomment and set values if you want to override defaults
#db.url=jdbc:mysql://localhost:3306/pharmacy_db
#db.user=root
#db.password=TB20010415

